# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Disable autocrlf
        run: git config --global core.autocrlf false
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup UCRT64 and Install Requirements
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          install: base-devel git
          pacboy: >-
            toolchain:p
            xpm-nox:p
            gmp:p
            gnutls:p
            libtiff:p
            giflib:p
            libpng:p
            libjpeg-turbo:p
            librsvg:p
            libwebp:p
            lcms2:p
            libxml2:p
            zlib:p
            harfbuzz:p
            libgccjit:p
            sqlite3:p
            tree-sitter:p
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        shell: msys2 {0}
        run: echo $MSYSTEM

      # Runs a set of commands using the runners shell
      - name: Clone Emacs 31
        shell: msys2 {0}
        run: |
          git config --global core.autocrlf false
          git clone https://github.com/emacs-mirror/emacs emacs-master
