name: CI for Building Emacs 31 with UCRT64

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Setup MSYS2 UCRT64 and Install the Necessary Packages
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          install: base-devel git
          pacboy: >-
            toolchain:p
            autotools:p
            xpm-nox:p
            gmp:p
            gnutls:p
            libtiff:p
            giflib:p
            libpng:p
            libjpeg-turbo:p
            librsvg:p
            libwebp:p
            lcms2:p
            libxml2:p
            zlib:p
            harfbuzz:p
            libgccjit:p
            sqlite3:p
            tree-sitter:p
      
      - name: Clone Emacs 31
        shell: msys2 {0}
        run: |
          git config --global core.autocrlf false
          git clone --depth 1 https://github.com/emacs-mirror/emacs emacs-master
      
      - name: Autogen and Configure
        shell: msys2 {0}
        run: |
          mkdir out
          cd emacs-master
          ./autogen.sh
          ./configure --prefix=$(realpath ../out) --without-imagemagick --without-dbus
      
      - name: Make
        shell: msys2 {0}
        run: |
          cd emacs-master
          make -j$(nproc)
      
      - name: Install
        shell: msys2 {0}
        run: |
          cd emacs-master
          make install
      
      - name: Test
        shell: msys2 {0}
        run: ./out/bin/runemacs.exe --version
